services:
  mcpo-control-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "8088:8088"
    # expose:
    #   - "8083"
    #   - "8088"
    volumes:
      - /home/mcpo:/data
      - /home:/home
      - /nas:/nas
      - /content:/content
      - /home/trav/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - /home/trav/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - '/box/Obsidian Vault:/obsidian'
    environment:
      MCPO_MANAGER_HOST: "0.0.0.0"
      MCPO_MANAGER_PORT: "8083"
      MCPO_MANAGER_DATA_DIR: "/data"
    restart: unless-stopped
    command:
      [
        "sh", "-c",
        "chmod 600 /root/.ssh/id_ed25519 && \
         chown root:root /root/.ssh/id_ed25519 && \
         uv run python -m mcpo_control_panel --host 0.0.0.0 --port 8083 --config-dir /data"
      ]
    labels:
      - glance.name=MCPO Control Panel
      - 'glance.url=http://mcpo.lab'
      - 'glance.description=Please dont paywall. Please dont paywall.'
      - glance.parent=openwebui
      - glance.category=ai
      - glance.hide=false